# ---
# kind: Namespace
# apiVersion: v1
# metadata:
#   name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
        tier: backend
    spec:
      containers:
      - name: redis-commander
        image: klmcwhirter/redis-commander
        env:
        - name: REDIS_HOSTS
          value: redis:6379
        ports:
        - name: redis-commander
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  namespace: redis
  labels:
    app: redis-commander
    tier: backend
spec:
  ports:
  - port: 8081
    targetPort: redis-commander
    name: redis-commander
  selector:
    app: redis-commander
    tier: backend
